a = {'  File "D:\\Anaconda\\lib\\threading.py", line 884, in _bootstrap\n    self._bootstrap_inner()\n',
     '  File "D:\\Anaconda\\lib\\threading.py", line 916, in _bootstrap_inner\n    self.run()\n',
     '  File "D:\\Anaconda\\lib\\threading.py", line 864, in run\n    self._target(*self._args, **self._kwargs)\n',
     '  File "D:\\Anaconda\\lib\\socketserver.py", line 639, in process_request_thread\n    self.finish_request(request, client_address)\n',
     '  File "D:\\Anaconda\\lib\\socketserver.py", line 361, in finish_request\n    self.RequestHandlerClass(request, client_address, self)\n',
     '  File "D:\\Anaconda\\lib\\socketserver.py", line 696, in __init__\n    self.handle()\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\servers\\basehttp.py", line 155, in handle\n    handler.run(self.server.get_app())\n',
     '  File "D:\\Anaconda\\lib\\wsgiref\\handlers.py", line 137, in run\n    self.result = application(self.environ, self.start_response)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\contrib\\staticfiles\\handlers.py", line 63, in __call__\n    return self.application(environ, start_response)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\wsgi.py", line 157, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\base.py", line 124, in get_response\n    response = self._middleware_chain(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\base.py", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\views\\decorators\\csrf.py", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\views\\generic\\base.py", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\views.py", line 491, in dispatch\n    self.initial(request, *args, **kwargs)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\views.py", line 405, in initial\n    self.check_permissions(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\views.py", line 333, in check_permissions\n    print(traceback.format_stack())\n'}

b = {'  File "D:\\Anaconda\\lib\\threading.py", line 884, in _bootstrap\n    self._bootstrap_inner()\n',
     '  File "D:\\Anaconda\\lib\\threading.py", line 916, in _bootstrap_inner\n    self.run()\n',
     '  File "D:\\Anaconda\\lib\\threading.py", line 864, in run\n    self._target(*self._args, **self._kwargs)\n',
     '  File "D:\\Anaconda\\lib\\socketserver.py", line 639, in process_request_thread\n    self.finish_request(request, client_address)\n',
     '  File "D:\\Anaconda\\lib\\socketserver.py", line 361, in finish_request\n    self.RequestHandlerClass(request, client_address, self)\n',
     '  File "D:\\Anaconda\\lib\\socketserver.py", line 696, in __init__\n    self.handle()\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\servers\\basehttp.py", line 155, in handle\n    handler.run(self.server.get_app())\n',
     '  File "D:\\Anaconda\\lib\\wsgiref\\handlers.py", line 137, in run\n    self.result = application(self.environ, self.start_response)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\contrib\\staticfiles\\handlers.py", line 63, in __call__\n    return self.application(environ, start_response)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\wsgi.py", line 157, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\base.py", line 124, in get_response\n    response = self._middleware_chain(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\utils\\deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 41, in inner\n    response = get_response(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\base.py", line 215, in _get_response\n    response = response.render()\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\django\\template\\response.py", line 107, in render\n    self.content = self.rendered_content\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\response.py", line 72, in rendered_content\n    ret = renderer.render(self.data, accepted_media_type, context)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 718, in render\n    context = self.get_context(data, accepted_media_type, renderer_context)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 693, in get_context\n    \'options_form\': self.get_rendered_html_form(data, view, \'OPTIONS\', request),\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 479, in get_rendered_html_form\n    if not self.show_form_for_method(view, method, request, instance):\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 434, in show_form_for_method\n    view.check_permissions(request)\n',
     '  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\views.py", line 333, in check_permissions\n    print(traceback.format_stack())\n'}

print(b - a)

c = {
'  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 718, in render\n    context = self.get_context(data, accepted_media_type, renderer_context)\n',
'  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 693, in get_context\n    \'options_form\': self.get_rendered_html_form(data, view, \'OPTIONS\', request),\n',
'  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 434, in show_form_for_method\n    view.check_permissions(request)\n',
'  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\response.py", line 72, in rendered_content\n    ret = renderer.render(self.data, accepted_media_type, context)\n',
'  File "D:\\Anaconda\\lib\\site-packages\\django\\core\\handlers\\base.py", line 215, in _get_response\n    response = response.render()\n',
'  File "D:\\Anaconda\\lib\\site-packages\\rest_framework\\renderers.py", line 479, in get_rendered_html_form\n    if not self.show_form_for_method(view, method, request, instance):\n',
'  File "D:\\Anaconda\\lib\\site-packages\\django\\template\\response.py", line 107, in render\n    self.content = self.rendered_content\n'}
